// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import LayoutsHeaderComponentController from '../../components/layouts/header/component';
application.register('layouts--header--component', LayoutsHeaderComponentController);

import LayoutsBreadcrumbComponentController from '../../components/layouts/breadcrumb/component';
application.register('layouts--breadcrumb--component', LayoutsBreadcrumbComponentController);

import LayoutsNotyfComponentController from '../../components/layouts/notyf/component';
application.register('layouts--notyf--component', LayoutsNotyfComponentController);
