// This file is auto-generated by ./bin/rails view_component:stimulus_manifest:update
// Run that command whenever you add a new controller in ViewComponent

import { application } from "../javascript/controllers/application"

import Layouts__Breadcrumb__ComponentController from "./layouts/breadcrumb/component_controller"
application.register("layouts--breadcrumb--component", Layouts__Breadcrumb__ComponentController)

import Layouts__Header__ComponentController from "./layouts/header/component_controller"
application.register("layouts--header--component", Layouts__Header__ComponentController)

import Layouts__Notyf__ComponentController from "./layouts/notyf/component_controller"
application.register("layouts--notyf--component", Layouts__Notyf__ComponentController)

import Tasks__Index__SearchCard__ComponentController from "./tasks/index/search_card/component_controller"
application.register("tasks--index--search-card--component", Tasks__Index__SearchCard__ComponentController)

import Tasks__Index__TaskListCard__ComponentController from "./tasks/index/task_list_card/component_controller"
application.register("tasks--index--task-list-card--component", Tasks__Index__TaskListCard__ComponentController)

import Users__SignIn__LoginCard__ComponentController from "./users/sign_in/login_card/component_controller"
application.register("users--sign-in--login-card--component", Users__SignIn__LoginCard__ComponentController)
