// This file is auto-generated by ./bin/rails view_component:stimulus_manifest:update
// Run that command whenever you add a new controller in ViewComponent

import { application } from "../javascript/controllers/application"

import Layouts__BreadcrumbController from "./layouts/breadcrumb_controller"
application.register("layouts--breadcrumb", Layouts__BreadcrumbController)

import Layouts__HeaderController from "./layouts/header_controller"
application.register("layouts--header", Layouts__HeaderController)

import Layouts__NotyfController from "./layouts/notyf_controller"
application.register("layouts--notyf", Layouts__NotyfController)

import Tasks__Index__SearchCardController from "./tasks/index/search_card_controller"
application.register("tasks--index--search-card", Tasks__Index__SearchCardController)

import Tasks__Index__TaskListCardController from "./tasks/index/task_list_card_controller"
application.register("tasks--index--task-list-card", Tasks__Index__TaskListCardController)
